# Configuration file for the authentication plugin "confauth"

production:
  # NOTE: localpart is prefixed to the domain. IE: {localpart}@example.com
  - localpart: test
    name: Test Account
    password: Password1

  - localpart: test2
    name: Test Account 2
    password: Password1

development:
  - localpart: test
    name: Test Account
    password: Password1

  - localpart: test2
    name: Test Account 2
    password: Password1
