# SMTP Server Port
port: 587

# hostname of this node. It MUST resolve to the IP of the server.
hostname: "192.168.1.202-ispgods.upperdomain.moredomain.prefixsuffix.com"

# maximum size of an email object
maxMailSize: 16777216

# Private/Public keys the server uses for listening.
SSLEnable: true
SSLKey: server.key
SSLCert: server.cert
SSLCa: false
